# Use this file as a starting point for your project's .eslintrc.
# Copy this file, and add rule overrides as needed.
---
extends: airbnb
parser: babel-eslint
rules:
  max-len:
  - error
  - 800
globals:
  window: true
  document: true
  _: true
  $: true
  istouch: true
  localStorage: true
  Hammer: true
env:
  es6: true
  browser: true
plugins:
- import
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    modules: true
    experimentalObjectRestSpread: true
